eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8760/eureka
  instance:
    hostname: localhost
spring:    
  zipkin:
    base-url: http://zipkin-server:9411/
