eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8760/eureka
  instance:
    hostname: eureka-0.eureka.default.svc.cluster.local
spring:    
  zipkin:
    base-url: http://zipkin-service-svc:80/
