eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
  instance:
    hostname: localhost
spring:    
  zipkin:
    base-url: http://127.0.0.1:9411/
